from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():

    return LaunchDescription([
        Node(
            package='create3_msg_transfer',
            executable='battery_state_subscriber',
            name='battery_state_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='cliff_intensity_subscriber',
            name='cliff_intensity_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='dock_status_subscriber',
            name='dock_status_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='imu_subscriber',
            name='imu_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='ir_intensity_subscriber',
            name='ir_intensity_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='ir_opcode_subscriber',
            name='ir_opcode_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='kidnap_status_subscriber',
            name='kidnap_status_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='mouse_subscriber',
            name='mouse_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='odom_subscriber',
            name='odom_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='slip_status_subscriber',
            name='slip_status_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='stop_status_subscriber',
            name='stop_status_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='tf_subscriber',
            name='tf_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='wheel_status_subscriber',
            name='wheel_status_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='wheel_ticks_subscriber',
            name='wheel_ticks_node',
            output='screen'
        ),
        Node(
            package='create3_msg_transfer',
            executable='wheel_vels_subscriber',
            name='wheel_vels_node',
            output='screen'
        )
    ])

if __name__ == '__main__':
    generate_launch_description()
